name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ] # Zadziała dla obu nazw gałęzi

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x # Upewnij się, że to Twoja wersja .NET

      - name: Publish .NET Core Project
        run: dotnet publish OutfitRandomizer.Client/OutfitRandomizer.Client.csproj -c Release -o release --nologo

      # GitHub Pages wymaga pliku .nojekyll, żeby poprawnie czytać foldery z podkreślnikami
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # Kopiujemy index.html do 404.html, żeby odświeżanie strony działało
      - name: Fix 404 redirection
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages # GitHub sam stworzy tę gałąź dla strony